### ISSUE TITLE
Local variables footer

### ISSUE THREAD

**Issue by raphywink** [stevecassidy/emuR#1]
Just wondering if [these](https://github.com/stevecassidy/emuR/blob/master/R/apply.R#L111) footers are still necessary or if they are just left over from the `S` days? I stumbled over them while cleaning up the IPS-LMU fork of this repo...

**Comment by stevecassidy** [comment]
They're from the old days when I used Emacs, a bit of history...but not
useful any more.

Steve

On 21 July 2014 21:39, Raphael Winkelmann notifications@github.com wrote:

> Just wondering if these
> https://github.com/stevecassidy/emuR/blob/master/R/apply.R#L111 footers
> are still necessary or if they are just left over from the S days? I
> stumbled over them while cleaning up the IPS-LMU fork of this repo...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stevecassidy/emuR/issues/1.

## 

Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy/

**Comment by raphywink** [comment]
Ok super! Then I'll just get rid of them (I'm in the process of converting all the .Rd files to Roxygen Docs... so I can ditch them while I'm doing that). 

Thanks
